// <auto-generated />
using System;
using Api.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.App.Auth.Entities.PermissionEntity", b =>
                {
                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id")
                        .HasComment("Manager/Admin who granted this permission");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Permission")
                        .HasColumnType("integer")
                        .HasColumnName("permission")
                        .HasComment("The specific permission type (e.g., Trade_Read, Admin_Write)");

                    b.Property<Guid?>("TargetIsId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_is_id")
                        .HasComment("Target user who possesses this permission");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Uuid")
                        .HasName("pk_permission");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_permission_created_by_id");

                    b.HasIndex("TargetIsId", "Permission")
                        .IsUnique()
                        .HasDatabaseName("ix_permission_target_is_id_permission");

                    b.ToTable("permission", null, t =>
                        {
                            t.HasComment("Fine-grained permission management table");
                        });
                });

            modelBuilder.Entity("Api.App.File.Entities.FileEntity", b =>
                {
                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Extension")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("extension")
                        .HasComment("File extension or MimeType");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name")
                        .HasComment("Storage-aliased filename");

                    b.Property<string>("OriginName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("origin_name")
                        .HasComment("Original filename from client");

                    b.Property<long?>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size")
                        .HasComment("File size in bytes");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type")
                        .HasComment("Storage visibility type (Public, Private, etc.)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("url")
                        .HasComment("Publicly accessible URL");

                    b.HasKey("Uuid")
                        .HasName("pk_file");

                    b.ToTable("file", null, t =>
                        {
                            t.HasComment("Metadata table for uploaded files (S3, etc.)");
                        });
                });

            modelBuilder.Entity("Api.App.User.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id")
                        .HasComment("Admin UUID who created this user");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Identify")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("identify")
                        .HasComment("User login login id (Unique)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at")
                        .HasComment("The last time the user logged in");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password")
                        .HasComment("Hashed password");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role")
                        .HasComment("User access level (Admin, SubAdmin, User)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Uuid")
                        .HasName("pk_user");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_user_created_by_id");

                    b.HasIndex("Identify")
                        .IsUnique()
                        .HasDatabaseName("ix_user_identify");

                    b.ToTable("user", null, t =>
                        {
                            t.HasComment("User Table for trading system");
                        });
                });

            modelBuilder.Entity("Api.App.Auth.Entities.PermissionEntity", b =>
                {
                    b.HasOne("Api.App.User.Entities.UserEntity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("fk_permission_user_created_by_id");

                    b.HasOne("Api.App.User.Entities.UserEntity", "TargetIs")
                        .WithMany()
                        .HasForeignKey("TargetIsId")
                        .HasConstraintName("fk_permission_user_target_is_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("TargetIs");
                });

            modelBuilder.Entity("Api.App.User.Entities.UserEntity", b =>
                {
                    b.HasOne("Api.App.User.Entities.UserEntity", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .HasConstraintName("fk_user_user_created_by_id");

                    b.Navigation("CreatedBy");
                });
#pragma warning restore 612, 618
        }
    }
}
